name: CI - Full Linux

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          #   - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-musl
        #   - target: x86_64-apple-darwin
        #   - target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@master

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-${{ matrix.target }}
          cache-on-failure: "true"

      - name: Compile
        id: compile
        if: ${{ matrix.target != 'x86_64-unknown-linux-musl' }}
        uses: oscartbeaumont/rust-build.action@master # rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none

      - name: Setup - x86_64-unknown-linux-musl
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        run: sudo apt-get install musl-tools

      - name: Compile - x86_64-unknown-linux-musl
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}

# TODO: These have the ugliest upload format, clean it up!
#   - name: Upload artifact
#     uses: actions/upload-artifact@v3
#     with:
#       name: Binary
#       path: |
#         ${{ steps.compile.outputs.BUILT_ARCHIVE }}
#         ${{ steps.compile.outputs.BUILT_CHECKSUM }}
